spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/COOPER_FILME
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
