spring:
  application:
    name: script-service

  datasource:
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/COOPER_FILME
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

logging:
  file:
    path: /logs
    name: /logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO